<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>SkyUI.Demo</RootNamespace>
    <AssemblyName>SkyUI.Demo</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkyUI.Core\SkyUI.Core.csproj" />
    <ProjectReference Include="..\SkyUI.Icons\SkyUI.Icons.csproj" />
    <ProjectReference Include="..\SkyUI\SkyUI.csproj" />
    <ProjectReference Include="..\SkyUI.Themes.Sky\SkyUI.Themes.Sky.csproj" />
    <ProjectReference Include="..\SkyUI.Data\SkyUI.Data.csproj" />
    <ProjectReference Include="..\SkyUI.Diagram\SkyUI.Diagram.csproj" />
  </ItemGroup>
</Project>
