<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AvaloniaVersion>12.1.1</AvaloniaVersion>
  </PropertyGroup>

  <Import Project="Directory.Pack.props" Condition="Exists('Directory.Pack.props')" />
</Project>
