<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0</TargetFrameworks>
    <RootNamespace>SkyUI.Demo.Mobile</RootNamespace>
    <AssemblyName>SkyUI.Demo.Mobile</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkyUI.Core\SkyUI.Core.csproj" />
    <ProjectReference Include="..\SkyUI.Fonts\SkyUI.Fonts.csproj" />
    <ProjectReference Include="..\SkyUI.Icons\SkyUI.Icons.csproj" />
    <ProjectReference Include="..\SkyUI\SkyUI.csproj" />
    <ProjectReference Include="..\SkyUI.Themes.Sky\SkyUI.Themes.Sky.csproj" />
  </ItemGroup>

</Project>
