<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-ios</TargetFramework>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>SkyUI.Demo.iOS</RootNamespace>
    <AssemblyName>SkyUI.Demo.iOS</AssemblyName>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">iossimulator-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.iOS" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkyUI.Demo.Mobile\SkyUI.Demo.Mobile.csproj" />
  </ItemGroup>

</Project>
