<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SkyUI</RootNamespace>
    <AssemblyName>SkyUI</AssemblyName>
    <Description>SkyUI essentials controls and default theme integration hooks.</Description>
    <IsPackable>true</IsPackable>
    <PackageId>SkyUI</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkyUI.Core\SkyUI.Core.csproj" />
    <ProjectReference Include="..\SkyUI.Icons\SkyUI.Icons.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SkyUI.UnitTests" />
    <InternalsVisibleTo Include="SkyUI.HeadlessTests" />
  </ItemGroup>

</Project>
